//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public string mahoadon { get; set; }
        public string mahd { get; set; }
        public string makh { get; set; }
        public string tenkh { get; set; }
        public string maxe { get; set; }
        public string tenxe { get; set; }
        public System.DateTime ngaylap { get; set; }
        public Nullable<int> tongtien { get; set; }
    
        public virtual khachhang khachhang { get; set; }
        public virtual Xe Xe { get; set; }
        public virtual hopdong hopdong { get; set; }
    }
}
