//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class hopdong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hopdong()
        {
            this.HoaDons = new HashSet<HoaDon>();
        }
    
        public string mahd { get; set; }
        public string maxe { get; set; }
        public string tenxe { get; set; }
        public string makh { get; set; }
        public string tenkh { get; set; }
        public System.DateTime ngaythue { get; set; }
        public System.DateTime ngaytra { get; set; }
        public Nullable<int> tienthue { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        public virtual Xe Xe { get; set; }
        public virtual khachhang khachhang { get; set; }
    }
}
